name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Veya kullanmakta olduğunuz dal adı

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Uygulamanızın ihtiyaç duyduğu Node.js sürümü

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Build edilen dosyaların yolu
